version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=superSecretDBPassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sprocket_db
    ports:
      - 5432:5432
    networks:
      - apishared-network
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

  server:
    container_name: sprocket-api
    restart: unless-stopped
    image: sprocket-api:1.0.0
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - apishared-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=placeholder@example.com
      - PGADMIN_DEFAULT_PASSWORD=fakepassword123!
    ports:
      - 16543:80
    depends_on:
      - db
    networks:
      - apishared-network

networks:
  apishared-network:
